ACCESS-NRI/schema

- au.org.access-nri/model/output/experiment-metadata/1-0-1.json
- au.org.access-nri/model/output/experiment-metadata/CHANGELOG.md
- au.org.access-nri/model/output/file-metadata/1-0-1.json
- au.org.access-nri/model/output/file-metadata/CHANGELOG.md
This PR adds new versions (1-0-1) of the `model/output/experiment-metadata` and `model/output/file-metadata` schema that include "wave" as an allowable `realm`.
Closes #10
> Add "wave" to list of allowable realms in metadata schema

- au.org.access-nri/model/output/experiment-metadata/1-0-2.json
- au.org.access-nri/model/output/experiment-metadata/CHANGELOG.md
This PR adds a version 1-0-2 of the `au.org.access-nri/model/output/experiment-metadata` schema that allows the model field to be an array or string (previously just array). We've chosen to do this because most experiment comprise only a single model.
Closes #11
> Allow model field to be array or string in experiment metadata

- au.org.access-nri/model/output/experiment-metadata/1-0-3.json
- au.org.access-nri/model/output/experiment-metadata/CHANGELOG.md
Add version of schema 1-0-3  of `experiment-metadata` schema, that allows `nominal_resolution` field to be a string or an array.
Closes #18
> experiment-metadata: allow nominal_resolution to be string or array

- au.org.access-nri/model/deployment/ config/versions/1-0-0.json
While testing out https://github.com/ACCESS-NRI/schema/pull/28 it was noted that the schema would always fail because `$schema` was required but not defined in properties, so it would automatically fail. Since this schema isn't in use yet, it should be able to be modified.
> `model/deployment/config/versions`: Added `$schema` as a required property

- au.org.access-nri/model/spack/environment/deployment/1-0-1.json
- au.org.access-nri/model/spack/environment/deployment/CHANGELOG.md
See related issue: https://github.com/ACCESS-NRI/spack-packages/issues/111
In this PR:
* We allow `=` in our version of `spack.yaml`, since we need to be able to `@git.TAG=VERSION` in our `spack.packages.*.requires[0]` statement.
> Added 1-0-1.json: Updated 'requires' regex

- .github/actions/validate-with-schema/README.md
- .github/actions/validate-with-schema/action.yml
- au.org.access-nri/model/configuration/ci/1-0-0.json
- au.org.access-nri/model/configuration/ci/CHANGELOG.md
- au.org.access-nri/model/configuration/ci/README.md
Moving the schema that was removed from https://github.com/ACCESS-NRI/access-om2-configs/pull/116 into here, and updating the action to allow for different metaschema versions. 
In this PR:
* Moved `ci.schema.json` into `au.org.access-nri/model/configuration/ci/1-0-0.json`, added `README.md` and `CHANGELOG.md`
* Updated `validate-with-schema` action to allow picking of metaschema version as the above schema is `2020-12`, not the default `draft07`
References ACCESS-NRI/model-config-tests#23
> Add `ci.schema.json` from `ACCESS-NRI/access-om2-configs`

- au.org.access-nri/model/spack/environment/deployment/1-0-2.json
- au.org.access-nri/model/spack/environment/deployment/CHANGELOG.md
See failed run: https://github.com/ACCESS-NRI/ACCESS-OM2/actions/runs/10416178348/job/28847949274
This PR updates the schema for our own restricted `spack.yaml`. Namely, `spack.packages.*.require[0]` now allows `/` in the version strings. This allows for branches such as `user/feature1` in package versions, like so: `@git.user/feature1`. 
In this PR:
* Update to a new schema version `1-0-2`
* Update CHANGELOG for `au.org.access-nri.model.spack.environment.deployment` schema
Since the diff doesn't help much, do `diff au.org.access-nri/model/spack/environment/deployment/1-0-1.json au.org.access-nri/model/spack/environment/deployment/1-0-2.json`. 
References https://github.com/ACCESS-NRI/ACCESS-OM2/pull/76
> Update `spack.packages.*.require[0]` to allow `/` in branches

- au.org.access-nri/model/configuration/ci/2-0-0.json
- au.org.access-nri/model/configuration/ci/CHANGELOG.md
Add a `payu-version` field to the `*-configs` repos `config/ci.json` schema.
Diffs are always funny with these schema updates, so run `diff au.org.access-nri/model/configuration/ci/1-0-0.json au.org.access-nri/model/configuration/ci/2-0-0.json`. 
In this PR:
* Updated `au.org.access-nri/model/configuration/ci` to `2-0-0`
* Added required `payu-version` field to all levels of configuration
* Updated CHANGELOG
References ACCESS-NRI/model-config-tests#37
> Add `payu-version` field to `configs/ci.json` schema

- .github/actions/validate-with-schema/action.yml
In this PR:
- Update the `git status` command that checks that the calling workflow has checked out a repository by having the `git` command run in the directory of the file of the `inputs.data-location`
Closes ACCESS-NRI/build-cd#133
> Fix for Finding Data Locations not at `.`

- au.org.access-nri/model/deployment/config/versions/2-0-0.json
- au.org.access-nri/model/deployment/config/versions/3-0-0.json
- au.org.access-nri/model/deployment/config/versions/CHANGELOG.md
Update the `au.org.access-nri/model/deployment/config/versions` schema to no longer include the required `spack-config` field, as that will now be handled by `build-cd`s `config/settings.json` file.
Also took the opportunity to update the `$id` field of the `2-0-0` version of the schema. 
See the diff properly with `diff -- au.org.access-nri/model/deployment/config/versions/2-0-0.json au.org.access-nri/model/deployment/config/versions/3-0-0.json`
In this PR:
- Add `au.org.access-nri/model/deployment/config/versions` schema `3-0-0`
- Update `au.org.access-nri/model/deployment/config/versions` schema `2-0-0`s `$id` field
References ACCESS-NRI/build-cd#123
> Deployment Repo `config/versions.json` Schema No Longer Requires `spack-config`

- au.org.access-nri/model/spack/environment/deployment/1-0-3.json
- au.org.access-nri/model/spack/environment/deployment/CHANGELOG.md
In this PR:
* Update `spack.yaml` deployment schema to allow for variants in the `spack.spec` string. 
* Also update the CHANGELOG
To see the diff better, since they are two different files, run `diff au.org.access-nri/model/spack/environment/deployment/1-0-2.json au.org.access-nri/model/spack/environment/deployment/1-0-3.json`
To use this version of the schema in your Model Deployment Repository, set the following variable: `gh variable set SPACK_YAML_SCHEMA_VERSION --body '1-0-3' --repo access-nri/MODEL`
References ACCESS-NRI/build-cd#180
> Update `au.org.access-nri/model/spack/environment/deployment` schema to `1-0-3`: Allow variants in spec string

- .github/workflows/validate-schema.yml
In `validate-schema.yml`: Add `-L` to curl command when downloading metaschema to follow re-directs. This is avoid schema urls such as `http://json-schema.org/draft-07/schema#` responding with `301 Moved Permanently` as it re-directs to the `https://` version of the url. 
Closes #40
> Fix validate-schema.yml metaschema download

- au.org.access-nri/model/spack/environment/deployment/1-0-3.json
- au.org.access-nri/model/spack/environment/deployment/1-0-4.json
- au.org.access-nri/model/spack/environment/deployment/CHANGELOG.md
References ACCESS-NRI/model-deployment-template#15
To diff this schema, do `diff -- au.org.access-nri/model/spack/environment/deployment/1-0-3.json au.org.access-nri/model/spack/environment/deployment/1-0-4.json` since it is a new file. 
This PR updates the schema that contains ACCESS-NRI-flavoured restrictions on `spack.yaml`. The changes are as follows:
* Update `spack.specs[]` to allow `"$ROOT_SPEC"` as a valid value
* Update `spack.definitions` to require definitions for `ROOT_PACKAGE`/`ROOT_SPEC` **only if** `spack.specs` contains `$ROOT_SPEC`
Also had some other changes:
- `1-0-3.json`: Update `$id` to be correctly referencing itself
- Updated `CHANGELOG.md`
Tested this schema against https://github.com/ACCESS-NRI/ACCESS-OM2/blob/multi-target-spack-yaml-format/spack.yaml, …
> Update schema to support multi-target `spack.yaml`

- au.org.access-nri/model/spack/environment/deployment/1-0-5.json
- au.org.access-nri/model/spack/environment/deployment/CHANGELOG.md
References ACCESS-NRI/build-cd#223
> [!NOTE]
> To view the diff properly (since `1-0-5.json` is a new file), run `git diff e9b7a72..bb16d04` or !github version!
This PR relaxes some of the constraints on the `spack.yaml`. 
In this PR:
- **Add 1-0-5.json as copy of 1-0-4.json**
- **Remove maximum-of-1 constraint on `spack.specs`**
- **Break on `=` after ref to explicitly support `=VERSION`**
- **Add type specifiers for strict-mode validation**
> Relax Constraints on `spack.specs`

- au.org.access-nri/model/spack/environment/deployment/1-0-6.json
- au.org.access-nri/model/spack/environment/deployment/CHANGELOG.md
Since we need to set `gcc-runtime`s compiler, but not the version (and indeed, the version for this package is generated dynamically (probably based on the compiler version)), we need to special case the `gcc-runtime` package to not be constrained by the `...requires[0] == @VERSION` check. I hope this is the only instance of the special case...
Actual schema changes are in https://github.com/ACCESS-NRI/schema/pull/44/commits/c5ab8f5f17f575729fbb45887eb3442a69b54d3b
In this PR:
- **Add 1-0-6.json based on 1-0-5.json**
- **Add in special case for dynamically-versioned `gcc-runtime` package**
- **Update Changelog**
Tested on https://github.com/ACCESS-NRI/ACCESS-OM3/blob/oneapi-test/spack.yaml with the first `gcc-runtime` requirement removed, using `ajv`: `ajv -d spack.yaml -s …
> `spack.yaml` schema: Special-case `spack.packages.gcc-runtime.requires[0]` requires no version 

- au.org.access-nri/model/spack/environment/deployment/1-0-7.json
- au.org.access-nri/model/spack/environment/deployment/CHANGELOG.md
References ACCESS-NRI/build-cd#234
Local `spack` builds using a `spack.yaml` need to use `@latest` because they can't reference a not-yet-existing `@git.TAG` like prerelease builds can. To allow continuity between these types, allow `@latest` in the schema. 
In this PR:
- **Add 1-0-7.json**
- **Allow `@latest` as a ref**
- **Update CHANGELOG**
> Allow `@latest` for `spack.specs[0]`

- au.org.access-nri/tracking_services/release_provenance/telemetry/1-0-0.json
- au.org.access-nri/tracking_services/release_provenance/telemetry/CHANGELOG.md
- au.org.access-nri/tracking_services/release_provenance/telemetry/README.md
Related to ACCESS-NRI/build-cd#263
Producer in progress at https://github.com/ACCESS-NRI/build-cd/tree/263-release-provenance-2.0
Consumer in https://github.com/ACCESS-NRI/tracking-services/pull/33
It would be useful to standardize on what data is produced and consumed relating to the release provenance database in a neutral third repository, so each side can validate it. This PR creates a first pass at the expected payload. 
* Add `1-0-0.json`, changelog and README.md
> Tracking Services: Release Provenance Payload Schema

- au.org.access-nri/tracking_services/release_provenance/telemetry/1-0-0.json
I'd erroneously had the module use/module load commands under the wrong database models. I've ninja edited the original `1-0-0` schema before we use it in production. 
* Swap `module use` and `module load` fields.
> Update 1-0-0 before use: Swap module use/load

- au.org.access-nri/tracking_services/release_provenance/telemetry/1-0-0.json
The old database kept track of URLs to the model components -  this should be the case for the current one, too.
> Add required repository_url to model component

- au.org.access-nri/model/deployment/config/auto-configs-pr/1-0-0.json
- au.org.access-nri/model/deployment/config/auto-configs-pr/CHANGELOG.md
- au.org.access-nri/model/deployment/config/auto-configs-pr/README.md
References ACCESS-NRI/build-cd#320
We need a schema to validate the MDRs `config/auto-configs-pr.json` configuration file, which is used to inform what PRs are opened from a given prerelease build. 
* Added initial schema, CHANGELOG and README
Validated against the example below with `jsonschema -i test.json au.org.access-nri/model/deployment/config/auto-configs-pr/1-0-0.json`:
```json
{
"$schema": "https://raw.githubusercontent.com/ACCESS-NRI/schema/main/au.org.access-nri/model/deployment/config/auto-configs-pr/1-0-0.json",
"profiles": {
"default": {
"configs_repo": "ACCESS-NRI/access-test-configs",
"configs": {
"dev-01deg_jra55_iaf": {
"checks": {
"repro": true
}
},
"dev-01deg_jra55_ryf": {
"checks": {
"repro": false
}
}
}
},
"qa-only": {
"configs_repo": …
```
> Add initial schema for MDRs `config/auto-configs-pr.json`
